version : "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file: .env
    image: mariadb
    restart: unless-stopped
    networks:
      - myNet
    volumes:
      - mariadb-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER_NAME", "-pMARIADB_USER_PSW"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    container_name: wordpress
    build: ./wordpress
    env_file: .env
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - myNet
    volumes:
      - wordpress-volume:/var/www/wordpress

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - myNet
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/wordpress

networks:
  myNet:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/ctirions/data/database
      type: volume
      o: bind

  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/ctirions/data/wordpress
      type: volume
      o: bind
