version: "3.9"
services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    env_file:
      - .env
    image: mariadb
    restart: unless-stopped
    networks:
      - inside
    volumes:
      - mariadb-volume:/var/lib/mysql/

  wordpress:
    container_name: wordpress
    build: ./wordpress/
    depends_on:
      - mariadb
    env_file:
      - .env
    image: wordpress
    restart: unless-stopped
    networks:
      - inside
    volumes:
      - wordpress-volume:/var/www/wordpress/

networks:
  inside:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/ctirions/data/database
      type: volume
      o: bind

  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/ctirions/data/wordpress
      type: volume
      o: bind
