UPDATE mysql.user SET Password = PASSWORD('$MARIADB_PSW') WHERE User = 'root';
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DROP DATABASE test;

CREATE DATABASE $MARIADB_DATABASE;
CREATE USER '$MARIADB_USER_NAME'@'%' IDENTIFIED BY '$MARIADB_USER_PSW';
GRANT ALL PRIVILEGES ON $MARIADB_NAME.* TO $MARIADB_USER_NAME@'%';

FLUSH PRIVILEGES;
